[options]
admin_passwd = $pbkdf2-sha512$600000$YOx9jxFiLMV4j9Eag9B6zw$GMYsppoULW/KYG1ErJSE2X8XL0wjB5Rsz27nxGK47y7hiIRe61vju09tpxxkG1o9fb9A8mP0liXUAgpi.55JGg
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons

